version: '2'

services:
 web1:
  image: amanu/php56-apache
  volumes:
   - ./final:/var/www/html/
  ports:
   - "8001:80"
  links:
   - "db1:sql"

 db1:
  build: .
  container_name: sql
  ports:
   - "3306:3306"
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_DATABASE: fransabadi
   MYSQL_ROOT_PASSWORD: digisof

volumes:
db_data: